[package]
name = "ahvm-netd-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
smoltcp = { version = "=0.14.0", default-features = false, features = ["std", "medium-ethernet", "proto-ipv4", "socket-tcp", "socket-udp"] }

[workspace]
members = ["."]

[[bin]]
name = "dns"
path = "fuzz_targets/dns.rs"
test = false
doc = false
bench = false

[[bin]]
name = "ingress"
path = "fuzz_targets/ingress.rs"
test = false
doc = false
bench = false
