#!/bin/bash
# Docker tier: minimal + Docker Engine + buildx.
# Sources minimal.sh first.
# Called by build-tier.sh with $MOUNT, $ARCH, $DEB_ARCH, $AGENT, $SCRIPT_DIR set.
#
# Kernel requirement: custom bhatti kernel with CONFIG_IP_NF_RAW=y,
# CONFIG_BRIDGE=y, CONFIG_VETH=y, CONFIG_OVERLAY_FS=y, CONFIG_NF_CONNTRACK=y,
# CONFIG_BINFMT_MISC=y. The first set is for Docker's bridge networking;
# BINFMT_MISC is for `docker buildx` cross-arch builds via qemu-user.
#
# Init model (per PLAN-tiers-systemd.md): dockerd is managed by lohar's
# systemctl shim via the upstream /lib/systemd/system/docker.service.
# We override two things via a drop-in because the shim deliberately
# does not implement systemd-style socket activation or D-Bus:
#   1. ExecStart loses `-H fd://` and binds the socket directly.
#      Rationale (PLAN-systemd-shims.md, "What's intentionally still
#      out"): "True socket activation is a lot of code for marginal
#      benefit." We hand dockerd the socket path instead.
#   2. daemon.json sets the cgroup driver to cgroupfs. The shim has
#      no D-Bus (PLAN-systemd-shims.md: "We don't run dbus-daemon and
#      don't intend to"). dockerd 29's default is the systemd cgroup
#      driver, which talks to systemd over D-Bus during every
#      container create. Without this override, `docker run` fails
#      with "dial unix /run/systemd/private: connect: no such file".
#   3. ExecStartPost chmods the socket 666 because `bhatti exec` runs
#      as uid 1000 without supplementary group membership (the docker
#      group is on the user but not picked up by lohar's exec path).
#      Safe in a single-user isolated VM.
set -euo pipefail

# Build minimal base first
"$SCRIPT_DIR/tiers/minimal.sh"

echo "==> Installing docker tier packages..."
chroot "$MOUNT" /bin/bash -c '
set -eu
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq

# Docker prerequisites
apt-get install -y --no-install-recommends \
    ca-certificates curl gnupg iptables

# Docker repo
curl -fsSL https://download.docker.com/linux/ubuntu/gpg \
    | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] \
    https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo $VERSION_CODENAME) stable" \
    > /etc/apt/sources.list.d/docker.list

apt-get update -qq
# docker-ce + buildx + compose. The buildx plugin is REQUIRED for
# `docker buildx build` to exist as a subcommand at all; the
# docker-ce package does not bundle it.
apt-get install -y --no-install-recommends \
    docker-ce docker-ce-cli containerd.io \
    docker-buildx-plugin docker-compose-plugin

# iptables-legacy: the bhatti kernel ships legacy iptables, not nft.
update-alternatives --set iptables /usr/sbin/iptables-legacy
update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy

# Add lohar user to docker group (kept for parity with standard
# Docker access control; the world-writable socket workaround in
# ExecStartPost is what actually grants uid-1000 access today).
usermod -aG docker lohar

apt-get clean
rm -rf /var/lib/apt/lists/*
'

# --- daemon.json: cgroupfs driver (no D-Bus available to talk to) ---
mkdir -p "$MOUNT/etc/docker"
cat > "$MOUNT/etc/docker/daemon.json" << 'DAEMON'
{
  "exec-opts": ["native.cgroupdriver=cgroupfs"]
}
DAEMON

# --- docker.service drop-in: kill -H fd://, add post-start chmod ---
#
# We do NOT ship our own docker.service. The upstream one from docker-ce
# is fine for everything except (a) the fd:// listener (needs systemd
# socket activation we don't have) and (b) the missing chmod hook.
# A drop-in is the systemd-canonical way to override those two lines.
mkdir -p "$MOUNT/etc/systemd/system/docker.service.d"
cat > "$MOUNT/etc/systemd/system/docker.service.d/bhatti.conf" << 'DROPIN'
# Generated by bhatti docker tier. See scripts/tiers/docker.sh.
[Service]
# Replace upstream `-H fd://` (requires socket activation lohar's
# systemctl shim doesn't implement) with a direct unix-socket bind.
ExecStart=
ExecStart=/usr/bin/dockerd -H unix:///var/run/docker.sock --containerd=/run/containerd/containerd.sock
# Pick up `bhatti create --env DOCKER_*=...` overrides via the
# config-env bridge written by lohar at boot. Optional file (leading
# '-'): minimal sandboxes without any --env flags still work.
EnvironmentFile=-/run/bhatti/config-env
# Widen the socket so `bhatti exec` (uid 1000, no supplementary groups)
# can reach it. Safe inside an isolated single-user microVM.
ExecStartPost=/bin/chmod 666 /var/run/docker.sock
# Restart on crash, but not so aggressively that a real bug masquerades
# as a flap. on-failure rather than always: lohar's watcher doesn't
# restart on clean exits, matching systemd's semantics.
Restart=on-failure
RestartSec=2s
DROPIN

# Defensive: make sure docker.service is in multi-user.target.wants.
# apt-installing docker-ce normally goes through deb-systemd-helper
# (and our systemctl shim) and creates this symlink. Cost of a
# defensive ln is zero; benefit is "tier still works if upstream
# postinst changes shape".
if [ ! -L "$MOUNT/etc/systemd/system/multi-user.target.wants/docker.service" ]; then
    ln -sf /lib/systemd/system/docker.service \
        "$MOUNT/etc/systemd/system/multi-user.target.wants/docker.service"
fi

# --- Drop the legacy init.sh path entirely ---
#
# Pre-v1.11.3 this tier started dockerd manually via /etc/bhatti/init.sh
# because the shim couldn't manage long-running daemons. The shim does
# now (per PLAN-systemd-shims.md F1-F6: cgroup-per-unit, Type=notify,
# After=/Before= ordering, ConditionPathExists=, EnvironmentFile=,
# tmpfiles.d). init.sh is no longer needed for this tier — it's still
# an optional extension point that downstream `bhatti image save`
# images can use, but we don't ship one.
rm -f "$MOUNT/etc/bhatti/init.sh"

echo "==> Docker tier done."
