[package]
name = "ahvm-engine"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"

[dev-dependencies]
ahvm-proto = { path = "../ahvm-proto" }
base64 = "0.22"
libc = "0.2"

[lints]
workspace = true
