[package]
name = "ahvm-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[[bin]]
name = "ahvm"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5", features = ["derive", "env"] }
reqwest = { version = "0.13", default-features = false, features = ["blocking", "json", "rustls"] }
serde_json = "1"
base64 = "0.23.1"
crossterm = "0.29"
tempfile = "3"
futures-util = "0.3"
tokio = { version = "1", features = ["rt", "time", "sync", "net", "macros"] }
tokio-tungstenite = { version = "0.29", features = ["rustls-tls-native-roots"] }
