[package]
name = "ahvm-cli"
version.workspace = true
edition.workspace = true
license-file.workspace = true

[lints]
workspace = true

[[bin]]
name = "ahvm"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5", features = ["derive", "env"] }
reqwest = { version = "0.13", default-features = false, features = ["blocking", "json", "rustls", "form"] }
serde_json = "1"
base64 = "0.23.1"
crossterm = "0.29"
tempfile = "3"
futures-util = "0.3"
tokio = { version = "1", features = ["rt", "time", "sync", "net", "macros"] }
tokio-tungstenite = { version = "0.29", features = ["rustls-tls-native-roots"] }
serde = { version = "1", features = ["derive"] }
fs2 = "0.4"
uuid = { version = "1", features = ["v4"] }
sha2 = "0.10"
ed25519-dalek = "2"
flate2 = "1"
semver = "1"
tar = "0.4"
oauth2 = { version = "5", default-features = false }
keyring = { version = "3.6.3", features = ["apple-native", "sync-secret-service", "crypto-rust", "vendored", "windows-native"] }
